"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let a = 3;
let b = 5;
console.log(a + b);
let c = 10;
let d = 2;
console.log(c - d);
let x = 2;
let y = 4;
console.log(2 * 4);
let e = 2;
let f = 16;
console.log(f / e);
